name = "ContextVariablesX"
uuid = "6add18c4-b38d-439d-96f6-d6bc489c04c5"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.1-DEV"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Compat = "3.3"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test"]
